version: "3.9"

services:
  devsecops:
    build:
      context: .
      dockerfile: dockerfile
    container_name: devsecops_training_backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
