version: "3.9"

services:
  devsecops:
    image: ghcr.io/reuter00/devsecopstraining:latest
    container_name: devsecops_backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgres://devuser:devpass@postgres:5432/devdb
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=devpass
      - POSTGRES_DB=devdb

  postgres:
    image: postgres:16-alpine
    container_name: devsecops_postgres
    restart: always
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: devdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  frontend:
    image: ghcr.io/reuter00/devsecopstraining-frontend:latest
    container_name: devsecops_frontend
    restart: always
    depends_on:
      - devsecops
    ports:
      - "8080:80"

volumes:
  postgres_data:
