global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'devsecops-api'
    metrics_path: /readyz
    static_configs:
      - targets: ['devsecops:3000']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres_exporter:9187']
